/* 
  *  This software is the property of Moon's Information Technology Ltd.
  * 
  *  All rights reserved.
  * 
  *  The software is only to be used for development and research purposes.
  *  Commercial use is only permitted under license or agreement.
  * 
  *  Copyright (C)  Moon's Information Technology Ltd.
  *  
  *  Author: rupert@moonsit.co.uk
  * 
  * 
 */
package uk.co.moons.gui.components;

import java.awt.Dimension;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import uk.co.moons.gui.components.testapps.ControlFunctionMonitor;
import uk.co.moons.gui.controlpanel.display.ControlDisplayTypes;

/**
 *
 * @author ReStart
 */
public class ControlFunctionView1 extends javax.swing.JPanel {

    private ControlFunctionMonitor function;
    private ControlDisplayTypes controlDisplayTypes;

    /** Creates new form ControlFunctionView1 */
    public ControlFunctionView1() {
        initComponents();
    }

    public void setControlFunction( ControlFunctionMonitor function) {
        this.function = function;

        // add listener to listen and react to changes in to value's state
        function.addPropertyChangeListener(new ControlListener() );
    }

    public void setLabel2Text(double value) {
        String text = String.valueOf(String.format("%5.2f", value));
        jLabel1.setText(text);
        //System.out.println("label " + jLabel1.getSize());
        double width = jPanelControlFunction.getSize().getWidth();
        double height = jPanelControlFunction.getSize().getHeight();
        double labelWidth = jLabel1.getSize().getWidth();
        double labelHeight = jLabel1.getSize().getHeight();
        if (labelWidth > width) {
            width = labelWidth;
        }
        if (labelHeight > height) {
            height = labelHeight;
        }
        //System.out.println("TEXT " + text);

        jPanelControlFunction.setBackground(controlDisplayTypes.getColor(value));
        jPanelControlFunction.setPreferredSize(new Dimension((int) width, (int) height));
        //this.revalidate();
        //this.repaint();
        //System.out.println("panel " + jPanelControlFunction.getSize());
    }

    public ControlDisplayTypes getControlDisplayTypes() {
        return controlDisplayTypes;
    }

    public void setControlDisplayTypes(ControlDisplayTypes controlDisplayTypes) {
        this.controlDisplayTypes = controlDisplayTypes;
    }

    /*
    @Override
    public void paintComponent(Graphics g) {
    System.out.println("paintComponent ");
    super.paintComponent(g);
    if (function != null) {
    String text = controlDisplayTypes.getText(function.getValue());
    System.out.println("TEXT1 " + text);
    Rectangle r = g.getClipBounds();
    g.setColor(new Color(240, 240, 240));
    g.fillRect(r.x, r.y, r.width, r.height);
    //jLabelValue.setBackground(Color.GRAY);
    //jLabelValue.setText(text);
    this.jLabel1.setText(text);
    this.jPanelControlFunction.setBackground(controlDisplayTypes.getColor(function.getValue()));
    }
    }*/
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelControlFunction = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setName("Form"); // NOI18N
        setPreferredSize(new java.awt.Dimension(20, 20));

        jPanelControlFunction.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelControlFunction.setName("jPanelControlFunction"); // NOI18N
        jPanelControlFunction.setPreferredSize(new java.awt.Dimension(40, 40));

        //jLabel1.setFont(org.jdesktop.application.Application.getInstance().getContext().getResourceMap(ControlFunctionView1.class).getFont("jLabel1.font")); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setLabelFor(jPanelControlFunction);
        //jLabel1.setText(org.jdesktop.application.Application.getInstance().getContext().getResourceMap(ControlFunctionView1.class).getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        jPanelControlFunction.add(jLabel1);

        add(jPanelControlFunction);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelControlFunction;
    // End of variables declaration//GEN-END:variables

    private class ControlListener implements PropertyChangeListener {

        @Override
        public void propertyChange(PropertyChangeEvent evt) {
            if (ControlFunctionMonitor.SYSTEM.equals(evt.getPropertyName())) {
                setLabel2Text(function.getInputControl().getValue());
            }
        }
    }
}
