/* 
  *  This software is the property of Moon's Information Technology Ltd.
  * 
  *  All rights reserved.
  * 
  *  The software is only to be used for development and research purposes.
  *  Commercial use is only permitted under license or agreement.
  * 
  *  Copyright (C)  Moon's Information Technology Ltd.
  *  
  *  Author: rupert@moonsit.co.uk
  * 
  * 
 */
package uk.co.moons.gui.components;

import java.util.HashMap;
import uk.co.moons.gui.controlpanel.display.ControlDisplayTypes;

/**
 *
 * @author ReStart
 */
public class ControlSystem extends javax.swing.JPanel {

    private pct.moons.co.uk.schema.layers.Layers.Layer.Controller pcontroller;
    private uk.co.moons.control.Controller controller;
    private HashMap<String, ControlDisplayTypes> cdt;
    private ControlHierarchyEventMonitor monitor;
    //private Boolean display = false;

    /**
     * Creates new form ControlSystem
     */
    public ControlSystem() {
        initComponents();
    }

    public ControlSystem(pct.moons.co.uk.schema.layers.Layers.Layer.Controller pcontroller, uk.co.moons.control.Controller controller, HashMap<String, ControlDisplayTypes> cdt, ControlHierarchyEventMonitor monitor) {
        this.pcontroller = pcontroller;
        this.controller = controller;
        this.cdt = cdt;
        this.monitor = monitor;
        initComponents();

    }

    public BooleanFlag getDisplay() {
        return controlSystemView.getDisplay();
    }

    //public void setDisplay(BooleanFlag display) {
      //  controlSystemView.setDisplay(display);
    //}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        controlSystemView = new uk.co.moons.gui.components.ControlSystemView();
        controlSystemView.setControlSystem(controller, cdt, monitor);

        setMaximumSize(new java.awt.Dimension(300, 2147483647));
        setName("Form"); // NOI18N
        setPreferredSize(new java.awt.Dimension(400, 253));
        setLayout(new java.awt.BorderLayout());

        controlSystemView.setMinimumSize(new java.awt.Dimension(10, 10));
        controlSystemView.setName("controlSystemView"); // NOI18N
        controlSystemView.setPreferredSize(new java.awt.Dimension(10, 20));
        add(controlSystemView, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private uk.co.moons.gui.components.ControlSystemView controlSystemView;
    // End of variables declaration//GEN-END:variables
}
